### ISSUE TITLE
Change license from GPL-3.0 to MIT

### ISSUE THREAD

**Issue by rsignell-usgs** [axiom-data-science/thredds_iso_harvester#3]
Is there any reason we can't change the license from GPL-3.0 to MIT?  
Unidata has a problem with GPL-3.0 (and nobody else seems to like it either) as [raised here](https://github.com/Unidata/thredds/issues/648#issuecomment-249926376)

**Comment by srstsavage** [comment]
@rsignell-usgs Yes, the reason is that the upstream [thredds_crawler](https://github.com/asascience-open/thredds_crawler) uses GPL 3. Can you create an issue there to change the license?

**Comment by srstsavage** [comment]
@rsignell-usgs Ok, thredds_crawler's license has been updated. Also updated this repo to the MIT license.
